version: '3.8'

services:
  web:
    container_name: app_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - .:/app:cached
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ~/.pycharm_helpers:/root/.pycharm_helpers
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - ENVIRONMENT=development
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=spend_time_together
    depends_on:
      - db
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=spend_time_together
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: