"""add fields to user tables

Revision ID: 3f684f72f4dc
Revises: ee3f5e9f14b0
Create Date: 2025-07-31 10:49:25.606699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f684f72f4dc'
down_revision: Union[str, Sequence[str], None] = 'ee3f5e9f14b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_link')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
