"""creator_user_id to activity

Revision ID: 9da90ff2d68e
Revises: 3f684f72f4dc
Create Date: 2025-08-06 10:55:07.748370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da90ff2d68e'
down_revision: Union[str, Sequence[str], None] = '3f684f72f4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('creator_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activity', 'users', ['creator_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'creator_user_id')
    # ### end Alembic commands ###
