"""add_user_variants_fields

Revision ID: b7abf1d9779a
Revises: 9da90ff2d68e
Create Date: 2025-08-07 09:35:00.042339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7abf1d9779a'
down_revision: Union[str, Sequence[str], None] = '9da90ff2d68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('platform_slug', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['user_activity_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['user_activity_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_activity', sa.Column('connections_count', sa.Integer(), nullable=False))
    op.add_column('user_activity_variants', sa.Column('api_game_id', sa.Integer(), nullable=False))
    op.add_column('user_activity_variants', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('user_activity_variants', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('user_activity_variants', sa.Column('background_image', sa.String(length=1024), nullable=True))
    op.add_column('user_activity_variants', sa.Column('background_image_additional', sa.String(length=1024), nullable=True))
    op.add_column('user_activity_variants', sa.Column('release_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_activity_variants', sa.Column('rating', sa.String(length=4), nullable=True))
    op.add_column('user_activity_variants', sa.Column('metacritic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity_variants', 'metacritic')
    op.drop_column('user_activity_variants', 'rating')
    op.drop_column('user_activity_variants', 'release_date')
    op.drop_column('user_activity_variants', 'background_image_additional')
    op.drop_column('user_activity_variants', 'background_image')
    op.drop_column('user_activity_variants', 'description')
    op.drop_column('user_activity_variants', 'name')
    op.drop_column('user_activity_variants', 'api_game_id')
    op.drop_column('user_activity', 'connections_count')
    op.drop_table('game_stores')
    op.drop_table('game_platforms')
    # ### end Alembic commands ###
